services:
  # 1. Database
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - mariadb-data:/var/lib/mysql

  # 2. DOMjudge Server (The Website)
  domserver:
    image: domjudge/domserver:8.3.1
    container_name: domserver
    ports:
      - "12345:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_ROOT_PASSWORD=rootpw
      - CONTAINER_TIMEZONE=Asia/Colombo 
    depends_on:
      - mariadb

volumes:
  mariadb-data: